### ISSUE TITLE
Change MOTD please

### ISSUE THREAD

**Issue by PerryPeak** [ImpactDevelopment/Resources#48]
Can you change the MOTD, please? I am from Israel and I get offended when someone says it is Palestine and not Israel and I don't want to stop using the client but I think I am going to do it, even if you wrote it as a joke (I don't support the people that say stuff like this on 2b2t, but this time, I like the client already and it is really annoying to suddenly see something like this)

**Comment by 5HT2** [comment]
hahaha holy shit lmaooo
if google says it's Palestine then it's politically correct 

please note: the above message was a clear joke with context from the private #staff channel in the impact discord

**Comment by 0-x-2-2** [comment]
Who let this "leijurv" antisemite have power! 👎

**Comment by ghost** [comment]
>I get offended when someone says it is Palestine and not Israel

Sounds like a you problem.

**Comment by XPLilith** [comment]
:cactus:

**Comment by LeafHacker** [comment]
> if google says it's Palestine then it's politically correct

don't forget google maps shows borders etc differently depending on where you are
